### ISSUE TITLE
banner capes

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#184]
they are so broken on 1.10.2 spigot i dont no were to start,
1: they dont appear on your character when you select one
2: they randomly appear and get stuck in the world but only other players can see them not the owner
see this pic of me wearing the ukflag banner, next to the banner of another player who over 300 blocks away in his plot,  https://gyazo.com/02ac8030c9767468805a9f82a1776388

**Comment by j0ach1mmall3** [comment]
Well, I'll see what I can do

**Comment by j0ach1mmall3** [comment]
> they are so broken on 1.10.2 spigot i dont no were to start,
1: they dont appear on your character when you select one
2: they randomly appear and get stuck in the world but only other players can see them not the owner
see this pic of me wearing the ukflag banner, next to the banner of another player who over 300 blocks away in his plot, https://gyazo.com/02ac8030c9767468805a9f82a1776388

Will be fixed in the newest update
